# Generated by Django 6.0 on 2025-12-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorydb',
            name='Description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
